language: node_js
node_js:
    - "6"

install:
    - npm install xvfb-maybe
    - npm install

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 -extension RANDR &

script:
    - npm run build
    - xvfb-maybe npm run coverage
    - npm run docs
